version: '3.8'
services:
  wquizz-app:
    image: wquizz:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"

  wquizz-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "placeholder2023"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"