version: '3.8'
services:

  wquizz-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    
  wquizz-app:
    image: mcgerasz/wquizz-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on: 
      - wquizz-db
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}

  wquizz-frontend:
    image: mcgerasz/wquizz-frontend:latest
    build:
      context: ../../../Frontend/quiz-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"