version: '3.8'
services:

  wquizz-db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password123"
    ports:
      - "1433:5432"
    
  wquizz-app:
    image: mcgerasz/wquizz-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on: 
      - wquizz-db
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      WQUIZZ_ADMINUSER_EMAIL: ${WQUIZZ_ADMINUSER_EMAIL}
      WQUIZZ_ADMINUSER_PASSWORD: ${WQUIZZ_ADMINUSER_PASSWORD}
      WQUIZZ_ADMINUSER_USERNAME: ${WQUIZZ_ADMINUSER_USERNAME}
      WQUIZZ_JWT_ISSUER_SIGNING_KEY: ${WQUIZZ_JWT_ISSUER_SIGNING_KEY}
      WQUIZZ_JWT_VALID_AUDIENCE: ${WQUIZZ_JWT_VALID_AUDIENCE}
      WQUIZZ_JWT_VALID_ISSUER: ${WQUIZZ_JWT_VALID_ISSUER}

  wquizz-frontend:
    image: mcgerasz/wquizz-frontend:latest
    build:
      context: ../../../Frontend/quiz-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"