name: Docker Compose Workflow

on:
  push:
    branches:
      - workflow/test-workflows

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version
        continue-on-error: true

      - name: Build and Start Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
        working-directory: Backend/QuizWebApp/QuizWebApp
        env:
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}

      - name: Wait for Database to be Ready
        run: |
          sleep 30

      - name: Run Tests
        run: |
          docker-compose exec -T wquizz-app sh -c 'dotnet restore QuizWebApp.sln'
          docker-compose exec -T wquizz-app sh -c 'dotnet test QuizWebApp.sln --no-restore --verbosity normal'
        working-directory: Backend/QuizWebApp
        env:
            ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}

      - name: Push Docker Compose Image to DockerHub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose push
        working-directory: Backend/QuizWebApp/QuizWebApp
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}