name: Docker Compose Workflow

on:
  push:
    branches:
      - main
      - backend/unit-test/non-auth

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Backend/QuizWebApp/QuizWebApp.sln
      - name: Build
        run: dotnet build Backend/QuizWebApp/QuizWebApp/QuizWebApp.csproj --no-restore
      - name: Test
        run: dotnet test Backend/QuizWebApp/QuizWebApp.sln --no-build --verbosity normal

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Compose
        run: docker-compose --version
        continue-on-error: true
      - name: Build and Start Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
        working-directory: Backend/QuizWebApp/QuizWebApp
        env:
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Push Docker Compose Image to DockerHub
        run: docker-compose push
        working-directory: Backend/QuizWebApp/QuizWebApp
        env:
          ASPNETCORE_CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}